openapi: '3.0.2'
info:
  title: Domofox  - Home thermostat API
  version: '1.0'
servers:
  - url: http://localhost/api
tags:
  - name: Device
    description: Device related commands
  - name: Heater
    description: Heater related commands
paths:
  /device/reboot:
    get:
      tags:
        - Device
      summary: Triggers device's reboot
      responses:
        '200':
          $ref: "#/components/responses/200"
        '500':
          $ref: "#/components/responses/500"
  /device/shutdown:
    get:
      tags:
        - Device
      summary: Triggers device's shutdown
      responses:
        '200':
          description: OK
  /heater/heating:
    get:
      tags:
        - Heater
      summary: Get the heater current state. Is it heating or not?
      responses:
        '200':
          description: Heater state is returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    enum: 
                      - true
                  value:
                    description: Heater state
                    type: boolean
        '500':
          $ref: "#/components/responses/500"
components:
  responses:
    200:
        description: Request succeeded
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/200"
    400:
        description: Request invalid
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/400"
    500:
        description: Internal error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/500"
  schemas:
    200: 
      type: object
      properties:
        result: 
          type: boolean
          enum: 
            - true
    400: 
      type: object
      properties:
        result: 
          type: boolean
          enum: 
            - false
        error: 
          type: string
    500: 
      type: object
      properties:
        result: 
          type: boolean
          enum: 
            - false
        error: 
          type: string