CREATE TABLE CONFIG (
    STRKEY TEXT PRIMARY KEY,
    STRVAL TEXT
);
INSERT INTO CONFIG (STRKEY, STRVAL) VALUES ("version", "1");

CREATE TABLE TRACES (
    CODTRACE TEXT PRIMARY KEY,
    LIBTRACE TEXT,
    RANGEMIN NUMERIC,
    RANGEMAX NUMERIC,
    COLOR    TEXT,
    CONSTANT INTEGER DEFAULT 0,
    FACTOR   NUMERIC DEFAULT 1,
    OFFSET   NUMERIC DEFAULT 0
);
INSERT INTO TRACES (CODTRACE, LIBTRACE, COLOR, CONSTANT) VALUES ("SETPOINT", "Setpoint", "blue", 1);
INSERT INTO TRACES (CODTRACE, LIBTRACE, COLOR, CONSTANT) VALUES ("AVG_TEMP", "Average temp.", "orange", 0);
INSERT INTO TRACES (CODTRACE, LIBTRACE, COLOR, CONSTANT) VALUES ("HEATER", "Heater state", "red", 1);

CREATE TABLE HISTDETAIL (
    NUMHIST INTEGER PRIMARY KEY AUTOINCREMENT,
    CODTRACE NUMERIC REFERENCES TRACES (CODTRACE),
    DATHIST TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMVALUE NUMERIC
);

CREATE TABLE HISTDAY (
    NUMHIST INTEGER PRIMARY KEY AUTOINCREMENT,
    CODTRACE NUMERIC REFERENCES TRACES (CODTRACE),
    DATHIST TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMVALUE NUMERIC
);

CREATE TABLE HISTMONTH (
    NUMHIST INTEGER PRIMARY KEY AUTOINCREMENT,
    CODTRACE NUMERIC REFERENCES TRACES (CODTRACE),
    DATHIST TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMVALUE NUMERIC
);

CREATE INDEX HISTDETAIL_IDX_DATHIST ON HISTDETAIL (DATHIST);
CREATE INDEX HISTDAY_IDX_DATHIST ON HISTDAY (DATHIST);
CREATE INDEX HISTMONTH_IDX_DATHIST ON HISTMONTH (DATHIST);